# CMake generated Testfile for 
# Source directory: /home/chenrui/catkin_ws/src/build_dir/source_dir/test
# Build directory: /home/chenrui/catkin_ws/src/build_dir/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(rand "rand")
SET_TESTS_PROPERTIES(rand PROPERTIES  LABELS "Official")
ADD_TEST(meta "meta")
SET_TESTS_PROPERTIES(meta PROPERTIES  LABELS "Official")
ADD_TEST(sizeof "sizeof")
SET_TESTS_PROPERTIES(sizeof PROPERTIES  LABELS "Official")
ADD_TEST(dynalloc "dynalloc")
SET_TESTS_PROPERTIES(dynalloc PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_1 "nomalloc_1")
SET_TESTS_PROPERTIES(nomalloc_1 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_2 "nomalloc_2")
SET_TESTS_PROPERTIES(nomalloc_2 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_3 "nomalloc_3")
SET_TESTS_PROPERTIES(nomalloc_3 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_4 "nomalloc_4")
SET_TESTS_PROPERTIES(nomalloc_4 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_5 "nomalloc_5")
SET_TESTS_PROPERTIES(nomalloc_5 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_6 "nomalloc_6")
SET_TESTS_PROPERTIES(nomalloc_6 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_7 "nomalloc_7")
SET_TESTS_PROPERTIES(nomalloc_7 PROPERTIES  LABELS "Official")
ADD_TEST(nomalloc_8 "nomalloc_8")
SET_TESTS_PROPERTIES(nomalloc_8 PROPERTIES  LABELS "Official")
ADD_TEST(first_aligned "first_aligned")
SET_TESTS_PROPERTIES(first_aligned PROPERTIES  LABELS "Official")
ADD_TEST(nullary_1 "nullary_1")
SET_TESTS_PROPERTIES(nullary_1 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_2 "nullary_2")
SET_TESTS_PROPERTIES(nullary_2 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_3 "nullary_3")
SET_TESTS_PROPERTIES(nullary_3 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_4 "nullary_4")
SET_TESTS_PROPERTIES(nullary_4 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_5 "nullary_5")
SET_TESTS_PROPERTIES(nullary_5 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_6 "nullary_6")
SET_TESTS_PROPERTIES(nullary_6 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_7 "nullary_7")
SET_TESTS_PROPERTIES(nullary_7 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_8 "nullary_8")
SET_TESTS_PROPERTIES(nullary_8 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_9 "nullary_9")
SET_TESTS_PROPERTIES(nullary_9 PROPERTIES  LABELS "Official")
ADD_TEST(nullary_10 "nullary_10")
SET_TESTS_PROPERTIES(nullary_10 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_1 "mixingtypes_1")
SET_TESTS_PROPERTIES(mixingtypes_1 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_2 "mixingtypes_2")
SET_TESTS_PROPERTIES(mixingtypes_2 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_3 "mixingtypes_3")
SET_TESTS_PROPERTIES(mixingtypes_3 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_4 "mixingtypes_4")
SET_TESTS_PROPERTIES(mixingtypes_4 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_5 "mixingtypes_5")
SET_TESTS_PROPERTIES(mixingtypes_5 PROPERTIES  LABELS "Official")
ADD_TEST(mixingtypes_6 "mixingtypes_6")
SET_TESTS_PROPERTIES(mixingtypes_6 PROPERTIES  LABELS "Official")
ADD_TEST(packetmath_1 "packetmath_1")
SET_TESTS_PROPERTIES(packetmath_1 PROPERTIES  LABELS "Official")
ADD_TEST(packetmath_2 "packetmath_2")
SET_TESTS_PROPERTIES(packetmath_2 PROPERTIES  LABELS "Official")
ADD_TEST(packetmath_3 "packetmath_3")
SET_TESTS_PROPERTIES(packetmath_3 PROPERTIES  LABELS "Official")
ADD_TEST(packetmath_4 "packetmath_4")
SET_TESTS_PROPERTIES(packetmath_4 PROPERTIES  LABELS "Official")
ADD_TEST(packetmath_5 "packetmath_5")
SET_TESTS_PROPERTIES(packetmath_5 PROPERTIES  LABELS "Official")
ADD_TEST(unalignedassert_1 "unalignedassert_1")
SET_TESTS_PROPERTIES(unalignedassert_1 PROPERTIES  LABELS "Official")
ADD_TEST(unalignedassert_2 "unalignedassert_2")
SET_TESTS_PROPERTIES(unalignedassert_2 PROPERTIES  LABELS "Official")
ADD_TEST(unalignedassert_3 "unalignedassert_3")
SET_TESTS_PROPERTIES(unalignedassert_3 PROPERTIES  LABELS "Official")
ADD_TEST(unalignedassert_4 "unalignedassert_4")
SET_TESTS_PROPERTIES(unalignedassert_4 PROPERTIES  LABELS "Official")
ADD_TEST(vectorization_logic_1 "vectorization_logic_1")
SET_TESTS_PROPERTIES(vectorization_logic_1 PROPERTIES  LABELS "Official")
ADD_TEST(vectorization_logic_2 "vectorization_logic_2")
SET_TESTS_PROPERTIES(vectorization_logic_2 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_2 "basicstuff_2")
SET_TESTS_PROPERTIES(basicstuff_2 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_1 "basicstuff_1")
SET_TESTS_PROPERTIES(basicstuff_1 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_3 "basicstuff_3")
SET_TESTS_PROPERTIES(basicstuff_3 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_4 "basicstuff_4")
SET_TESTS_PROPERTIES(basicstuff_4 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_5 "basicstuff_5")
SET_TESTS_PROPERTIES(basicstuff_5 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_6 "basicstuff_6")
SET_TESTS_PROPERTIES(basicstuff_6 PROPERTIES  LABELS "Official")
ADD_TEST(basicstuff_7 "basicstuff_7")
SET_TESTS_PROPERTIES(basicstuff_7 PROPERTIES  LABELS "Official")
ADD_TEST(constructor_1 "constructor_1")
SET_TESTS_PROPERTIES(constructor_1 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_1 "linearstructure_1")
SET_TESTS_PROPERTIES(linearstructure_1 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_2 "linearstructure_2")
SET_TESTS_PROPERTIES(linearstructure_2 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_3 "linearstructure_3")
SET_TESTS_PROPERTIES(linearstructure_3 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_4 "linearstructure_4")
SET_TESTS_PROPERTIES(linearstructure_4 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_5 "linearstructure_5")
SET_TESTS_PROPERTIES(linearstructure_5 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_6 "linearstructure_6")
SET_TESTS_PROPERTIES(linearstructure_6 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_7 "linearstructure_7")
SET_TESTS_PROPERTIES(linearstructure_7 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_8 "linearstructure_8")
SET_TESTS_PROPERTIES(linearstructure_8 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_9 "linearstructure_9")
SET_TESTS_PROPERTIES(linearstructure_9 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_10 "linearstructure_10")
SET_TESTS_PROPERTIES(linearstructure_10 PROPERTIES  LABELS "Official")
ADD_TEST(linearstructure_11 "linearstructure_11")
SET_TESTS_PROPERTIES(linearstructure_11 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_1 "integer_types_1")
SET_TESTS_PROPERTIES(integer_types_1 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_2 "integer_types_2")
SET_TESTS_PROPERTIES(integer_types_2 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_3 "integer_types_3")
SET_TESTS_PROPERTIES(integer_types_3 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_4 "integer_types_4")
SET_TESTS_PROPERTIES(integer_types_4 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_5 "integer_types_5")
SET_TESTS_PROPERTIES(integer_types_5 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_6 "integer_types_6")
SET_TESTS_PROPERTIES(integer_types_6 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_7 "integer_types_7")
SET_TESTS_PROPERTIES(integer_types_7 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_8 "integer_types_8")
SET_TESTS_PROPERTIES(integer_types_8 PROPERTIES  LABELS "Official")
ADD_TEST(integer_types_9 "integer_types_9")
SET_TESTS_PROPERTIES(integer_types_9 PROPERTIES  LABELS "Official")
ADD_TEST(unalignedcount "unalignedcount")
SET_TESTS_PROPERTIES(unalignedcount PROPERTIES  LABELS "Official")
ADD_TEST(exceptions "exceptions")
SET_TESTS_PROPERTIES(exceptions PROPERTIES  LABELS "Official")
ADD_TEST(redux_1 "redux_1")
SET_TESTS_PROPERTIES(redux_1 PROPERTIES  LABELS "Official")
ADD_TEST(redux_2 "redux_2")
SET_TESTS_PROPERTIES(redux_2 PROPERTIES  LABELS "Official")
ADD_TEST(redux_3 "redux_3")
SET_TESTS_PROPERTIES(redux_3 PROPERTIES  LABELS "Official")
ADD_TEST(redux_4 "redux_4")
SET_TESTS_PROPERTIES(redux_4 PROPERTIES  LABELS "Official")
ADD_TEST(redux_5 "redux_5")
SET_TESTS_PROPERTIES(redux_5 PROPERTIES  LABELS "Official")
ADD_TEST(redux_6 "redux_6")
SET_TESTS_PROPERTIES(redux_6 PROPERTIES  LABELS "Official")
ADD_TEST(redux_7 "redux_7")
SET_TESTS_PROPERTIES(redux_7 PROPERTIES  LABELS "Official")
ADD_TEST(redux_8 "redux_8")
SET_TESTS_PROPERTIES(redux_8 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_1 "visitor_1")
SET_TESTS_PROPERTIES(visitor_1 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_2 "visitor_2")
SET_TESTS_PROPERTIES(visitor_2 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_3 "visitor_3")
SET_TESTS_PROPERTIES(visitor_3 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_4 "visitor_4")
SET_TESTS_PROPERTIES(visitor_4 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_5 "visitor_5")
SET_TESTS_PROPERTIES(visitor_5 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_6 "visitor_6")
SET_TESTS_PROPERTIES(visitor_6 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_7 "visitor_7")
SET_TESTS_PROPERTIES(visitor_7 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_8 "visitor_8")
SET_TESTS_PROPERTIES(visitor_8 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_9 "visitor_9")
SET_TESTS_PROPERTIES(visitor_9 PROPERTIES  LABELS "Official")
ADD_TEST(visitor_10 "visitor_10")
SET_TESTS_PROPERTIES(visitor_10 PROPERTIES  LABELS "Official")
ADD_TEST(block_1 "block_1")
SET_TESTS_PROPERTIES(block_1 PROPERTIES  LABELS "Official")
ADD_TEST(block_2 "block_2")
SET_TESTS_PROPERTIES(block_2 PROPERTIES  LABELS "Official")
ADD_TEST(block_3 "block_3")
SET_TESTS_PROPERTIES(block_3 PROPERTIES  LABELS "Official")
ADD_TEST(block_4 "block_4")
SET_TESTS_PROPERTIES(block_4 PROPERTIES  LABELS "Official")
ADD_TEST(block_5 "block_5")
SET_TESTS_PROPERTIES(block_5 PROPERTIES  LABELS "Official")
ADD_TEST(block_6 "block_6")
SET_TESTS_PROPERTIES(block_6 PROPERTIES  LABELS "Official")
ADD_TEST(block_8 "block_8")
SET_TESTS_PROPERTIES(block_8 PROPERTIES  LABELS "Official")
ADD_TEST(block_7 "block_7")
SET_TESTS_PROPERTIES(block_7 PROPERTIES  LABELS "Official")
ADD_TEST(corners_1 "corners_1")
SET_TESTS_PROPERTIES(corners_1 PROPERTIES  LABELS "Official")
ADD_TEST(corners_2 "corners_2")
SET_TESTS_PROPERTIES(corners_2 PROPERTIES  LABELS "Official")
ADD_TEST(corners_3 "corners_3")
SET_TESTS_PROPERTIES(corners_3 PROPERTIES  LABELS "Official")
ADD_TEST(corners_4 "corners_4")
SET_TESTS_PROPERTIES(corners_4 PROPERTIES  LABELS "Official")
ADD_TEST(corners_5 "corners_5")
SET_TESTS_PROPERTIES(corners_5 PROPERTIES  LABELS "Official")
ADD_TEST(swap_1 "swap_1")
SET_TESTS_PROPERTIES(swap_1 PROPERTIES  LABELS "Official")
ADD_TEST(swap_2 "swap_2")
SET_TESTS_PROPERTIES(swap_2 PROPERTIES  LABELS "Official")
ADD_TEST(swap_3 "swap_3")
SET_TESTS_PROPERTIES(swap_3 PROPERTIES  LABELS "Official")
ADD_TEST(swap_4 "swap_4")
SET_TESTS_PROPERTIES(swap_4 PROPERTIES  LABELS "Official")
ADD_TEST(resize "resize")
SET_TESTS_PROPERTIES(resize PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_1 "conservative_resize_1")
SET_TESTS_PROPERTIES(conservative_resize_1 PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_2 "conservative_resize_2")
SET_TESTS_PROPERTIES(conservative_resize_2 PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_3 "conservative_resize_3")
SET_TESTS_PROPERTIES(conservative_resize_3 PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_4 "conservative_resize_4")
SET_TESTS_PROPERTIES(conservative_resize_4 PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_5 "conservative_resize_5")
SET_TESTS_PROPERTIES(conservative_resize_5 PROPERTIES  LABELS "Official")
ADD_TEST(conservative_resize_6 "conservative_resize_6")
SET_TESTS_PROPERTIES(conservative_resize_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_1 "product_small_1")
SET_TESTS_PROPERTIES(product_small_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_2 "product_small_2")
SET_TESTS_PROPERTIES(product_small_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_8 "product_small_8")
SET_TESTS_PROPERTIES(product_small_8 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_3 "product_small_3")
SET_TESTS_PROPERTIES(product_small_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_4 "product_small_4")
SET_TESTS_PROPERTIES(product_small_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_5 "product_small_5")
SET_TESTS_PROPERTIES(product_small_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_6 "product_small_6")
SET_TESTS_PROPERTIES(product_small_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_11 "product_small_11")
SET_TESTS_PROPERTIES(product_small_11 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_12 "product_small_12")
SET_TESTS_PROPERTIES(product_small_12 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_13 "product_small_13")
SET_TESTS_PROPERTIES(product_small_13 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_21 "product_small_21")
SET_TESTS_PROPERTIES(product_small_21 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_22 "product_small_22")
SET_TESTS_PROPERTIES(product_small_22 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_23 "product_small_23")
SET_TESTS_PROPERTIES(product_small_23 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_31 "product_small_31")
SET_TESTS_PROPERTIES(product_small_31 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_32 "product_small_32")
SET_TESTS_PROPERTIES(product_small_32 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_33 "product_small_33")
SET_TESTS_PROPERTIES(product_small_33 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_41 "product_small_41")
SET_TESTS_PROPERTIES(product_small_41 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_42 "product_small_42")
SET_TESTS_PROPERTIES(product_small_42 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_43 "product_small_43")
SET_TESTS_PROPERTIES(product_small_43 PROPERTIES  LABELS "Official")
ADD_TEST(product_small_7 "product_small_7")
SET_TESTS_PROPERTIES(product_small_7 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_1 "product_large_1")
SET_TESTS_PROPERTIES(product_large_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_2 "product_large_2")
SET_TESTS_PROPERTIES(product_large_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_3 "product_large_3")
SET_TESTS_PROPERTIES(product_large_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_4 "product_large_4")
SET_TESTS_PROPERTIES(product_large_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_5 "product_large_5")
SET_TESTS_PROPERTIES(product_large_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_large_6 "product_large_6")
SET_TESTS_PROPERTIES(product_large_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_1 "product_extra_1")
SET_TESTS_PROPERTIES(product_extra_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_2 "product_extra_2")
SET_TESTS_PROPERTIES(product_extra_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_3 "product_extra_3")
SET_TESTS_PROPERTIES(product_extra_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_4 "product_extra_4")
SET_TESTS_PROPERTIES(product_extra_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_5 "product_extra_5")
SET_TESTS_PROPERTIES(product_extra_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_6 "product_extra_6")
SET_TESTS_PROPERTIES(product_extra_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_7 "product_extra_7")
SET_TESTS_PROPERTIES(product_extra_7 PROPERTIES  LABELS "Official")
ADD_TEST(product_extra_8 "product_extra_8")
SET_TESTS_PROPERTIES(product_extra_8 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_1 "diagonalmatrices_1")
SET_TESTS_PROPERTIES(diagonalmatrices_1 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_2 "diagonalmatrices_2")
SET_TESTS_PROPERTIES(diagonalmatrices_2 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_3 "diagonalmatrices_3")
SET_TESTS_PROPERTIES(diagonalmatrices_3 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_4 "diagonalmatrices_4")
SET_TESTS_PROPERTIES(diagonalmatrices_4 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_5 "diagonalmatrices_5")
SET_TESTS_PROPERTIES(diagonalmatrices_5 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_6 "diagonalmatrices_6")
SET_TESTS_PROPERTIES(diagonalmatrices_6 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_7 "diagonalmatrices_7")
SET_TESTS_PROPERTIES(diagonalmatrices_7 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_8 "diagonalmatrices_8")
SET_TESTS_PROPERTIES(diagonalmatrices_8 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_9 "diagonalmatrices_9")
SET_TESTS_PROPERTIES(diagonalmatrices_9 PROPERTIES  LABELS "Official")
ADD_TEST(diagonalmatrices_10 "diagonalmatrices_10")
SET_TESTS_PROPERTIES(diagonalmatrices_10 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_1 "adjoint_1")
SET_TESTS_PROPERTIES(adjoint_1 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_2 "adjoint_2")
SET_TESTS_PROPERTIES(adjoint_2 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_3 "adjoint_3")
SET_TESTS_PROPERTIES(adjoint_3 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_4 "adjoint_4")
SET_TESTS_PROPERTIES(adjoint_4 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_5 "adjoint_5")
SET_TESTS_PROPERTIES(adjoint_5 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_6 "adjoint_6")
SET_TESTS_PROPERTIES(adjoint_6 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_8 "adjoint_8")
SET_TESTS_PROPERTIES(adjoint_8 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_9 "adjoint_9")
SET_TESTS_PROPERTIES(adjoint_9 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_10 "adjoint_10")
SET_TESTS_PROPERTIES(adjoint_10 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_11 "adjoint_11")
SET_TESTS_PROPERTIES(adjoint_11 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_12 "adjoint_12")
SET_TESTS_PROPERTIES(adjoint_12 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_7 "adjoint_7")
SET_TESTS_PROPERTIES(adjoint_7 PROPERTIES  LABELS "Official")
ADD_TEST(adjoint_13 "adjoint_13")
SET_TESTS_PROPERTIES(adjoint_13 PROPERTIES  LABELS "Official")
ADD_TEST(diagonal_1 "diagonal_1")
SET_TESTS_PROPERTIES(diagonal_1 PROPERTIES  LABELS "Official")
ADD_TEST(diagonal_2 "diagonal_2")
SET_TESTS_PROPERTIES(diagonal_2 PROPERTIES  LABELS "Official")
ADD_TEST(miscmatrices_1 "miscmatrices_1")
SET_TESTS_PROPERTIES(miscmatrices_1 PROPERTIES  LABELS "Official")
ADD_TEST(miscmatrices_2 "miscmatrices_2")
SET_TESTS_PROPERTIES(miscmatrices_2 PROPERTIES  LABELS "Official")
ADD_TEST(miscmatrices_3 "miscmatrices_3")
SET_TESTS_PROPERTIES(miscmatrices_3 PROPERTIES  LABELS "Official")
ADD_TEST(miscmatrices_4 "miscmatrices_4")
SET_TESTS_PROPERTIES(miscmatrices_4 PROPERTIES  LABELS "Official")
ADD_TEST(miscmatrices_5 "miscmatrices_5")
SET_TESTS_PROPERTIES(miscmatrices_5 PROPERTIES  LABELS "Official")
ADD_TEST(commainitializer "commainitializer")
SET_TESTS_PROPERTIES(commainitializer PROPERTIES  LABELS "Official")
ADD_TEST(smallvectors "smallvectors")
SET_TESTS_PROPERTIES(smallvectors PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_1 "mapped_matrix_1")
SET_TESTS_PROPERTIES(mapped_matrix_1 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_2 "mapped_matrix_2")
SET_TESTS_PROPERTIES(mapped_matrix_2 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_3 "mapped_matrix_3")
SET_TESTS_PROPERTIES(mapped_matrix_3 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_4 "mapped_matrix_4")
SET_TESTS_PROPERTIES(mapped_matrix_4 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_5 "mapped_matrix_5")
SET_TESTS_PROPERTIES(mapped_matrix_5 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_11 "mapped_matrix_11")
SET_TESTS_PROPERTIES(mapped_matrix_11 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_6 "mapped_matrix_6")
SET_TESTS_PROPERTIES(mapped_matrix_6 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_7 "mapped_matrix_7")
SET_TESTS_PROPERTIES(mapped_matrix_7 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_8 "mapped_matrix_8")
SET_TESTS_PROPERTIES(mapped_matrix_8 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_9 "mapped_matrix_9")
SET_TESTS_PROPERTIES(mapped_matrix_9 PROPERTIES  LABELS "Official")
ADD_TEST(mapped_matrix_10 "mapped_matrix_10")
SET_TESTS_PROPERTIES(mapped_matrix_10 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_1 "mapstride_1")
SET_TESTS_PROPERTIES(mapstride_1 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_2 "mapstride_2")
SET_TESTS_PROPERTIES(mapstride_2 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_3 "mapstride_3")
SET_TESTS_PROPERTIES(mapstride_3 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_4 "mapstride_4")
SET_TESTS_PROPERTIES(mapstride_4 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_5 "mapstride_5")
SET_TESTS_PROPERTIES(mapstride_5 PROPERTIES  LABELS "Official")
ADD_TEST(mapstride_6 "mapstride_6")
SET_TESTS_PROPERTIES(mapstride_6 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_1 "mapstaticmethods_1")
SET_TESTS_PROPERTIES(mapstaticmethods_1 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_2 "mapstaticmethods_2")
SET_TESTS_PROPERTIES(mapstaticmethods_2 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_3 "mapstaticmethods_3")
SET_TESTS_PROPERTIES(mapstaticmethods_3 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_4 "mapstaticmethods_4")
SET_TESTS_PROPERTIES(mapstaticmethods_4 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_5 "mapstaticmethods_5")
SET_TESTS_PROPERTIES(mapstaticmethods_5 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_6 "mapstaticmethods_6")
SET_TESTS_PROPERTIES(mapstaticmethods_6 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_7 "mapstaticmethods_7")
SET_TESTS_PROPERTIES(mapstaticmethods_7 PROPERTIES  LABELS "Official")
ADD_TEST(mapstaticmethods_8 "mapstaticmethods_8")
SET_TESTS_PROPERTIES(mapstaticmethods_8 PROPERTIES  LABELS "Official")
ADD_TEST(array_1 "array_1")
SET_TESTS_PROPERTIES(array_1 PROPERTIES  LABELS "Official")
ADD_TEST(array_2 "array_2")
SET_TESTS_PROPERTIES(array_2 PROPERTIES  LABELS "Official")
ADD_TEST(array_3 "array_3")
SET_TESTS_PROPERTIES(array_3 PROPERTIES  LABELS "Official")
ADD_TEST(array_4 "array_4")
SET_TESTS_PROPERTIES(array_4 PROPERTIES  LABELS "Official")
ADD_TEST(array_5 "array_5")
SET_TESTS_PROPERTIES(array_5 PROPERTIES  LABELS "Official")
ADD_TEST(array_6 "array_6")
SET_TESTS_PROPERTIES(array_6 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_1 "array_for_matrix_1")
SET_TESTS_PROPERTIES(array_for_matrix_1 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_2 "array_for_matrix_2")
SET_TESTS_PROPERTIES(array_for_matrix_2 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_3 "array_for_matrix_3")
SET_TESTS_PROPERTIES(array_for_matrix_3 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_4 "array_for_matrix_4")
SET_TESTS_PROPERTIES(array_for_matrix_4 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_5 "array_for_matrix_5")
SET_TESTS_PROPERTIES(array_for_matrix_5 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_6 "array_for_matrix_6")
SET_TESTS_PROPERTIES(array_for_matrix_6 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_7 "array_for_matrix_7")
SET_TESTS_PROPERTIES(array_for_matrix_7 PROPERTIES  LABELS "Official")
ADD_TEST(array_for_matrix_8 "array_for_matrix_8")
SET_TESTS_PROPERTIES(array_for_matrix_8 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_1 "array_replicate_1")
SET_TESTS_PROPERTIES(array_replicate_1 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_2 "array_replicate_2")
SET_TESTS_PROPERTIES(array_replicate_2 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_3 "array_replicate_3")
SET_TESTS_PROPERTIES(array_replicate_3 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_4 "array_replicate_4")
SET_TESTS_PROPERTIES(array_replicate_4 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_5 "array_replicate_5")
SET_TESTS_PROPERTIES(array_replicate_5 PROPERTIES  LABELS "Official")
ADD_TEST(array_replicate_6 "array_replicate_6")
SET_TESTS_PROPERTIES(array_replicate_6 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_1 "array_reverse_1")
SET_TESTS_PROPERTIES(array_reverse_1 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_2 "array_reverse_2")
SET_TESTS_PROPERTIES(array_reverse_2 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_3 "array_reverse_3")
SET_TESTS_PROPERTIES(array_reverse_3 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_4 "array_reverse_4")
SET_TESTS_PROPERTIES(array_reverse_4 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_5 "array_reverse_5")
SET_TESTS_PROPERTIES(array_reverse_5 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_6 "array_reverse_6")
SET_TESTS_PROPERTIES(array_reverse_6 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_7 "array_reverse_7")
SET_TESTS_PROPERTIES(array_reverse_7 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_8 "array_reverse_8")
SET_TESTS_PROPERTIES(array_reverse_8 PROPERTIES  LABELS "Official")
ADD_TEST(array_reverse_9 "array_reverse_9")
SET_TESTS_PROPERTIES(array_reverse_9 PROPERTIES  LABELS "Official")
ADD_TEST(ref_1 "ref_1")
SET_TESTS_PROPERTIES(ref_1 PROPERTIES  LABELS "Official")
ADD_TEST(ref_2 "ref_2")
SET_TESTS_PROPERTIES(ref_2 PROPERTIES  LABELS "Official")
ADD_TEST(ref_3 "ref_3")
SET_TESTS_PROPERTIES(ref_3 PROPERTIES  LABELS "Official")
ADD_TEST(ref_4 "ref_4")
SET_TESTS_PROPERTIES(ref_4 PROPERTIES  LABELS "Official")
ADD_TEST(ref_5 "ref_5")
SET_TESTS_PROPERTIES(ref_5 PROPERTIES  LABELS "Official")
ADD_TEST(ref_6 "ref_6")
SET_TESTS_PROPERTIES(ref_6 PROPERTIES  LABELS "Official")
ADD_TEST(ref_7 "ref_7")
SET_TESTS_PROPERTIES(ref_7 PROPERTIES  LABELS "Official")
ADD_TEST(is_same_dense "is_same_dense")
SET_TESTS_PROPERTIES(is_same_dense PROPERTIES  LABELS "Official")
ADD_TEST(triangular_1 "triangular_1")
SET_TESTS_PROPERTIES(triangular_1 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_2 "triangular_2")
SET_TESTS_PROPERTIES(triangular_2 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_3 "triangular_3")
SET_TESTS_PROPERTIES(triangular_3 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_4 "triangular_4")
SET_TESTS_PROPERTIES(triangular_4 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_5 "triangular_5")
SET_TESTS_PROPERTIES(triangular_5 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_6 "triangular_6")
SET_TESTS_PROPERTIES(triangular_6 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_7 "triangular_7")
SET_TESTS_PROPERTIES(triangular_7 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_8 "triangular_8")
SET_TESTS_PROPERTIES(triangular_8 PROPERTIES  LABELS "Official")
ADD_TEST(triangular_9 "triangular_9")
SET_TESTS_PROPERTIES(triangular_9 PROPERTIES  LABELS "Official")
ADD_TEST(selfadjoint_1 "selfadjoint_1")
SET_TESTS_PROPERTIES(selfadjoint_1 PROPERTIES  LABELS "Official")
ADD_TEST(selfadjoint_2 "selfadjoint_2")
SET_TESTS_PROPERTIES(selfadjoint_2 PROPERTIES  LABELS "Official")
ADD_TEST(selfadjoint_3 "selfadjoint_3")
SET_TESTS_PROPERTIES(selfadjoint_3 PROPERTIES  LABELS "Official")
ADD_TEST(selfadjoint_4 "selfadjoint_4")
SET_TESTS_PROPERTIES(selfadjoint_4 PROPERTIES  LABELS "Official")
ADD_TEST(selfadjoint_5 "selfadjoint_5")
SET_TESTS_PROPERTIES(selfadjoint_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_1 "product_selfadjoint_1")
SET_TESTS_PROPERTIES(product_selfadjoint_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_2 "product_selfadjoint_2")
SET_TESTS_PROPERTIES(product_selfadjoint_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_3 "product_selfadjoint_3")
SET_TESTS_PROPERTIES(product_selfadjoint_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_4 "product_selfadjoint_4")
SET_TESTS_PROPERTIES(product_selfadjoint_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_5 "product_selfadjoint_5")
SET_TESTS_PROPERTIES(product_selfadjoint_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_6 "product_selfadjoint_6")
SET_TESTS_PROPERTIES(product_selfadjoint_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_selfadjoint_7 "product_selfadjoint_7")
SET_TESTS_PROPERTIES(product_selfadjoint_7 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_1 "product_symm_1")
SET_TESTS_PROPERTIES(product_symm_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_2 "product_symm_2")
SET_TESTS_PROPERTIES(product_symm_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_3 "product_symm_3")
SET_TESTS_PROPERTIES(product_symm_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_4 "product_symm_4")
SET_TESTS_PROPERTIES(product_symm_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_5 "product_symm_5")
SET_TESTS_PROPERTIES(product_symm_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_6 "product_symm_6")
SET_TESTS_PROPERTIES(product_symm_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_7 "product_symm_7")
SET_TESTS_PROPERTIES(product_symm_7 PROPERTIES  LABELS "Official")
ADD_TEST(product_symm_8 "product_symm_8")
SET_TESTS_PROPERTIES(product_symm_8 PROPERTIES  LABELS "Official")
ADD_TEST(product_syrk_1 "product_syrk_1")
SET_TESTS_PROPERTIES(product_syrk_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_syrk_2 "product_syrk_2")
SET_TESTS_PROPERTIES(product_syrk_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_syrk_3 "product_syrk_3")
SET_TESTS_PROPERTIES(product_syrk_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_syrk_4 "product_syrk_4")
SET_TESTS_PROPERTIES(product_syrk_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_1 "product_trmv_1")
SET_TESTS_PROPERTIES(product_trmv_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_2 "product_trmv_2")
SET_TESTS_PROPERTIES(product_trmv_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_3 "product_trmv_3")
SET_TESTS_PROPERTIES(product_trmv_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_4 "product_trmv_4")
SET_TESTS_PROPERTIES(product_trmv_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_5 "product_trmv_5")
SET_TESTS_PROPERTIES(product_trmv_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmv_6 "product_trmv_6")
SET_TESTS_PROPERTIES(product_trmv_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_1 "product_trmm_1")
SET_TESTS_PROPERTIES(product_trmm_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_11 "product_trmm_11")
SET_TESTS_PROPERTIES(product_trmm_11 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_111 "product_trmm_111")
SET_TESTS_PROPERTIES(product_trmm_111 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_21 "product_trmm_21")
SET_TESTS_PROPERTIES(product_trmm_21 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_121 "product_trmm_121")
SET_TESTS_PROPERTIES(product_trmm_121 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_31 "product_trmm_31")
SET_TESTS_PROPERTIES(product_trmm_31 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_131 "product_trmm_131")
SET_TESTS_PROPERTIES(product_trmm_131 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_12 "product_trmm_12")
SET_TESTS_PROPERTIES(product_trmm_12 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_112 "product_trmm_112")
SET_TESTS_PROPERTIES(product_trmm_112 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_22 "product_trmm_22")
SET_TESTS_PROPERTIES(product_trmm_22 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_122 "product_trmm_122")
SET_TESTS_PROPERTIES(product_trmm_122 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_32 "product_trmm_32")
SET_TESTS_PROPERTIES(product_trmm_32 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_132 "product_trmm_132")
SET_TESTS_PROPERTIES(product_trmm_132 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_13 "product_trmm_13")
SET_TESTS_PROPERTIES(product_trmm_13 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_113 "product_trmm_113")
SET_TESTS_PROPERTIES(product_trmm_113 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_23 "product_trmm_23")
SET_TESTS_PROPERTIES(product_trmm_23 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_123 "product_trmm_123")
SET_TESTS_PROPERTIES(product_trmm_123 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_33 "product_trmm_33")
SET_TESTS_PROPERTIES(product_trmm_33 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_133 "product_trmm_133")
SET_TESTS_PROPERTIES(product_trmm_133 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_14 "product_trmm_14")
SET_TESTS_PROPERTIES(product_trmm_14 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_114 "product_trmm_114")
SET_TESTS_PROPERTIES(product_trmm_114 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_24 "product_trmm_24")
SET_TESTS_PROPERTIES(product_trmm_24 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_124 "product_trmm_124")
SET_TESTS_PROPERTIES(product_trmm_124 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_34 "product_trmm_34")
SET_TESTS_PROPERTIES(product_trmm_34 PROPERTIES  LABELS "Official")
ADD_TEST(product_trmm_134 "product_trmm_134")
SET_TESTS_PROPERTIES(product_trmm_134 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_1 "product_trsolve_1")
SET_TESTS_PROPERTIES(product_trsolve_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_2 "product_trsolve_2")
SET_TESTS_PROPERTIES(product_trsolve_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_3 "product_trsolve_3")
SET_TESTS_PROPERTIES(product_trsolve_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_4 "product_trsolve_4")
SET_TESTS_PROPERTIES(product_trsolve_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_5 "product_trsolve_5")
SET_TESTS_PROPERTIES(product_trsolve_5 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_6 "product_trsolve_6")
SET_TESTS_PROPERTIES(product_trsolve_6 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_7 "product_trsolve_7")
SET_TESTS_PROPERTIES(product_trsolve_7 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_8 "product_trsolve_8")
SET_TESTS_PROPERTIES(product_trsolve_8 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_9 "product_trsolve_9")
SET_TESTS_PROPERTIES(product_trsolve_9 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_10 "product_trsolve_10")
SET_TESTS_PROPERTIES(product_trsolve_10 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_11 "product_trsolve_11")
SET_TESTS_PROPERTIES(product_trsolve_11 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_12 "product_trsolve_12")
SET_TESTS_PROPERTIES(product_trsolve_12 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_13 "product_trsolve_13")
SET_TESTS_PROPERTIES(product_trsolve_13 PROPERTIES  LABELS "Official")
ADD_TEST(product_trsolve_14 "product_trsolve_14")
SET_TESTS_PROPERTIES(product_trsolve_14 PROPERTIES  LABELS "Official")
ADD_TEST(product_mmtr_1 "product_mmtr_1")
SET_TESTS_PROPERTIES(product_mmtr_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_mmtr_2 "product_mmtr_2")
SET_TESTS_PROPERTIES(product_mmtr_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_mmtr_3 "product_mmtr_3")
SET_TESTS_PROPERTIES(product_mmtr_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_mmtr_4 "product_mmtr_4")
SET_TESTS_PROPERTIES(product_mmtr_4 PROPERTIES  LABELS "Official")
ADD_TEST(product_notemporary_1 "product_notemporary_1")
SET_TESTS_PROPERTIES(product_notemporary_1 PROPERTIES  LABELS "Official")
ADD_TEST(product_notemporary_2 "product_notemporary_2")
SET_TESTS_PROPERTIES(product_notemporary_2 PROPERTIES  LABELS "Official")
ADD_TEST(product_notemporary_3 "product_notemporary_3")
SET_TESTS_PROPERTIES(product_notemporary_3 PROPERTIES  LABELS "Official")
ADD_TEST(product_notemporary_4 "product_notemporary_4")
SET_TESTS_PROPERTIES(product_notemporary_4 PROPERTIES  LABELS "Official")
ADD_TEST(stable_norm_1 "stable_norm_1")
SET_TESTS_PROPERTIES(stable_norm_1 PROPERTIES  LABELS "Official")
ADD_TEST(stable_norm_2 "stable_norm_2")
SET_TESTS_PROPERTIES(stable_norm_2 PROPERTIES  LABELS "Official")
ADD_TEST(stable_norm_3 "stable_norm_3")
SET_TESTS_PROPERTIES(stable_norm_3 PROPERTIES  LABELS "Official")
ADD_TEST(stable_norm_4 "stable_norm_4")
SET_TESTS_PROPERTIES(stable_norm_4 PROPERTIES  LABELS "Official")
ADD_TEST(stable_norm_5 "stable_norm_5")
SET_TESTS_PROPERTIES(stable_norm_5 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_1 "permutationmatrices_1")
SET_TESTS_PROPERTIES(permutationmatrices_1 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_2 "permutationmatrices_2")
SET_TESTS_PROPERTIES(permutationmatrices_2 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_3 "permutationmatrices_3")
SET_TESTS_PROPERTIES(permutationmatrices_3 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_4 "permutationmatrices_4")
SET_TESTS_PROPERTIES(permutationmatrices_4 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_5 "permutationmatrices_5")
SET_TESTS_PROPERTIES(permutationmatrices_5 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_6 "permutationmatrices_6")
SET_TESTS_PROPERTIES(permutationmatrices_6 PROPERTIES  LABELS "Official")
ADD_TEST(permutationmatrices_7 "permutationmatrices_7")
SET_TESTS_PROPERTIES(permutationmatrices_7 PROPERTIES  LABELS "Official")
ADD_TEST(bandmatrix "bandmatrix")
SET_TESTS_PROPERTIES(bandmatrix PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_1 "cholesky_1")
SET_TESTS_PROPERTIES(cholesky_1 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_3 "cholesky_3")
SET_TESTS_PROPERTIES(cholesky_3 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_4 "cholesky_4")
SET_TESTS_PROPERTIES(cholesky_4 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_5 "cholesky_5")
SET_TESTS_PROPERTIES(cholesky_5 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_2 "cholesky_2")
SET_TESTS_PROPERTIES(cholesky_2 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_6 "cholesky_6")
SET_TESTS_PROPERTIES(cholesky_6 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_7 "cholesky_7")
SET_TESTS_PROPERTIES(cholesky_7 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_8 "cholesky_8")
SET_TESTS_PROPERTIES(cholesky_8 PROPERTIES  LABELS "Official")
ADD_TEST(cholesky_9 "cholesky_9")
SET_TESTS_PROPERTIES(cholesky_9 PROPERTIES  LABELS "Official")
ADD_TEST(lu_1 "lu_1")
SET_TESTS_PROPERTIES(lu_1 PROPERTIES  LABELS "Official")
ADD_TEST(lu_2 "lu_2")
SET_TESTS_PROPERTIES(lu_2 PROPERTIES  LABELS "Official")
ADD_TEST(lu_3 "lu_3")
SET_TESTS_PROPERTIES(lu_3 PROPERTIES  LABELS "Official")
ADD_TEST(lu_4 "lu_4")
SET_TESTS_PROPERTIES(lu_4 PROPERTIES  LABELS "Official")
ADD_TEST(lu_5 "lu_5")
SET_TESTS_PROPERTIES(lu_5 PROPERTIES  LABELS "Official")
ADD_TEST(lu_6 "lu_6")
SET_TESTS_PROPERTIES(lu_6 PROPERTIES  LABELS "Official")
ADD_TEST(lu_7 "lu_7")
SET_TESTS_PROPERTIES(lu_7 PROPERTIES  LABELS "Official")
ADD_TEST(lu_9 "lu_9")
SET_TESTS_PROPERTIES(lu_9 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_1 "determinant_1")
SET_TESTS_PROPERTIES(determinant_1 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_2 "determinant_2")
SET_TESTS_PROPERTIES(determinant_2 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_3 "determinant_3")
SET_TESTS_PROPERTIES(determinant_3 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_4 "determinant_4")
SET_TESTS_PROPERTIES(determinant_4 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_5 "determinant_5")
SET_TESTS_PROPERTIES(determinant_5 PROPERTIES  LABELS "Official")
ADD_TEST(determinant_6 "determinant_6")
SET_TESTS_PROPERTIES(determinant_6 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_5 "inverse_5")
SET_TESTS_PROPERTIES(inverse_5 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_6 "inverse_6")
SET_TESTS_PROPERTIES(inverse_6 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_1 "inverse_1")
SET_TESTS_PROPERTIES(inverse_1 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_2 "inverse_2")
SET_TESTS_PROPERTIES(inverse_2 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_3 "inverse_3")
SET_TESTS_PROPERTIES(inverse_3 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_4 "inverse_4")
SET_TESTS_PROPERTIES(inverse_4 PROPERTIES  LABELS "Official")
ADD_TEST(inverse_7 "inverse_7")
SET_TESTS_PROPERTIES(inverse_7 PROPERTIES  LABELS "Official")
ADD_TEST(qr_1 "qr_1")
SET_TESTS_PROPERTIES(qr_1 PROPERTIES  LABELS "Official")
ADD_TEST(qr_2 "qr_2")
SET_TESTS_PROPERTIES(qr_2 PROPERTIES  LABELS "Official")
ADD_TEST(qr_3 "qr_3")
SET_TESTS_PROPERTIES(qr_3 PROPERTIES  LABELS "Official")
ADD_TEST(qr_4 "qr_4")
SET_TESTS_PROPERTIES(qr_4 PROPERTIES  LABELS "Official")
ADD_TEST(qr_5 "qr_5")
SET_TESTS_PROPERTIES(qr_5 PROPERTIES  LABELS "Official")
ADD_TEST(qr_11 "qr_11")
SET_TESTS_PROPERTIES(qr_11 PROPERTIES  LABELS "Official")
ADD_TEST(qr_6 "qr_6")
SET_TESTS_PROPERTIES(qr_6 PROPERTIES  LABELS "Official")
ADD_TEST(qr_7 "qr_7")
SET_TESTS_PROPERTIES(qr_7 PROPERTIES  LABELS "Official")
ADD_TEST(qr_8 "qr_8")
SET_TESTS_PROPERTIES(qr_8 PROPERTIES  LABELS "Official")
ADD_TEST(qr_9 "qr_9")
SET_TESTS_PROPERTIES(qr_9 PROPERTIES  LABELS "Official")
ADD_TEST(qr_10 "qr_10")
SET_TESTS_PROPERTIES(qr_10 PROPERTIES  LABELS "Official")
ADD_TEST(qr_12 "qr_12")
SET_TESTS_PROPERTIES(qr_12 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_1 "qr_colpivoting_1")
SET_TESTS_PROPERTIES(qr_colpivoting_1 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_2 "qr_colpivoting_2")
SET_TESTS_PROPERTIES(qr_colpivoting_2 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_3 "qr_colpivoting_3")
SET_TESTS_PROPERTIES(qr_colpivoting_3 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_4 "qr_colpivoting_4")
SET_TESTS_PROPERTIES(qr_colpivoting_4 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_5 "qr_colpivoting_5")
SET_TESTS_PROPERTIES(qr_colpivoting_5 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_6 "qr_colpivoting_6")
SET_TESTS_PROPERTIES(qr_colpivoting_6 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_7 "qr_colpivoting_7")
SET_TESTS_PROPERTIES(qr_colpivoting_7 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_8 "qr_colpivoting_8")
SET_TESTS_PROPERTIES(qr_colpivoting_8 PROPERTIES  LABELS "Official")
ADD_TEST(qr_colpivoting_9 "qr_colpivoting_9")
SET_TESTS_PROPERTIES(qr_colpivoting_9 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_1 "qr_fullpivoting_1")
SET_TESTS_PROPERTIES(qr_fullpivoting_1 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_2 "qr_fullpivoting_2")
SET_TESTS_PROPERTIES(qr_fullpivoting_2 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_3 "qr_fullpivoting_3")
SET_TESTS_PROPERTIES(qr_fullpivoting_3 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_4 "qr_fullpivoting_4")
SET_TESTS_PROPERTIES(qr_fullpivoting_4 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_5 "qr_fullpivoting_5")
SET_TESTS_PROPERTIES(qr_fullpivoting_5 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_6 "qr_fullpivoting_6")
SET_TESTS_PROPERTIES(qr_fullpivoting_6 PROPERTIES  LABELS "Official")
ADD_TEST(qr_fullpivoting_7 "qr_fullpivoting_7")
SET_TESTS_PROPERTIES(qr_fullpivoting_7 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_1 "upperbidiagonalization_1")
SET_TESTS_PROPERTIES(upperbidiagonalization_1 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_2 "upperbidiagonalization_2")
SET_TESTS_PROPERTIES(upperbidiagonalization_2 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_3 "upperbidiagonalization_3")
SET_TESTS_PROPERTIES(upperbidiagonalization_3 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_4 "upperbidiagonalization_4")
SET_TESTS_PROPERTIES(upperbidiagonalization_4 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_5 "upperbidiagonalization_5")
SET_TESTS_PROPERTIES(upperbidiagonalization_5 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_6 "upperbidiagonalization_6")
SET_TESTS_PROPERTIES(upperbidiagonalization_6 PROPERTIES  LABELS "Official")
ADD_TEST(upperbidiagonalization_7 "upperbidiagonalization_7")
SET_TESTS_PROPERTIES(upperbidiagonalization_7 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_1 "hessenberg_1")
SET_TESTS_PROPERTIES(hessenberg_1 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_2 "hessenberg_2")
SET_TESTS_PROPERTIES(hessenberg_2 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_3 "hessenberg_3")
SET_TESTS_PROPERTIES(hessenberg_3 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_4 "hessenberg_4")
SET_TESTS_PROPERTIES(hessenberg_4 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_5 "hessenberg_5")
SET_TESTS_PROPERTIES(hessenberg_5 PROPERTIES  LABELS "Official")
ADD_TEST(hessenberg_6 "hessenberg_6")
SET_TESTS_PROPERTIES(hessenberg_6 PROPERTIES  LABELS "Official")
ADD_TEST(schur_real_1 "schur_real_1")
SET_TESTS_PROPERTIES(schur_real_1 PROPERTIES  LABELS "Official")
ADD_TEST(schur_real_2 "schur_real_2")
SET_TESTS_PROPERTIES(schur_real_2 PROPERTIES  LABELS "Official")
ADD_TEST(schur_real_3 "schur_real_3")
SET_TESTS_PROPERTIES(schur_real_3 PROPERTIES  LABELS "Official")
ADD_TEST(schur_real_4 "schur_real_4")
SET_TESTS_PROPERTIES(schur_real_4 PROPERTIES  LABELS "Official")
ADD_TEST(schur_real_5 "schur_real_5")
SET_TESTS_PROPERTIES(schur_real_5 PROPERTIES  LABELS "Official")
ADD_TEST(schur_complex_1 "schur_complex_1")
SET_TESTS_PROPERTIES(schur_complex_1 PROPERTIES  LABELS "Official")
ADD_TEST(schur_complex_2 "schur_complex_2")
SET_TESTS_PROPERTIES(schur_complex_2 PROPERTIES  LABELS "Official")
ADD_TEST(schur_complex_3 "schur_complex_3")
SET_TESTS_PROPERTIES(schur_complex_3 PROPERTIES  LABELS "Official")
ADD_TEST(schur_complex_4 "schur_complex_4")
SET_TESTS_PROPERTIES(schur_complex_4 PROPERTIES  LABELS "Official")
ADD_TEST(schur_complex_5 "schur_complex_5")
SET_TESTS_PROPERTIES(schur_complex_5 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_1 "eigensolver_selfadjoint_1")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_1 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_12 "eigensolver_selfadjoint_12")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_12 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_13 "eigensolver_selfadjoint_13")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_13 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_2 "eigensolver_selfadjoint_2")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_2 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_3 "eigensolver_selfadjoint_3")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_3 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_4 "eigensolver_selfadjoint_4")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_4 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_5 "eigensolver_selfadjoint_5")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_5 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_9 "eigensolver_selfadjoint_9")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_9 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_6 "eigensolver_selfadjoint_6")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_6 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_7 "eigensolver_selfadjoint_7")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_7 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_selfadjoint_8 "eigensolver_selfadjoint_8")
SET_TESTS_PROPERTIES(eigensolver_selfadjoint_8 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generic_1 "eigensolver_generic_1")
SET_TESTS_PROPERTIES(eigensolver_generic_1 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generic_2 "eigensolver_generic_2")
SET_TESTS_PROPERTIES(eigensolver_generic_2 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generic_3 "eigensolver_generic_3")
SET_TESTS_PROPERTIES(eigensolver_generic_3 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generic_4 "eigensolver_generic_4")
SET_TESTS_PROPERTIES(eigensolver_generic_4 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generic_5 "eigensolver_generic_5")
SET_TESTS_PROPERTIES(eigensolver_generic_5 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_complex_1 "eigensolver_complex_1")
SET_TESTS_PROPERTIES(eigensolver_complex_1 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_complex_2 "eigensolver_complex_2")
SET_TESTS_PROPERTIES(eigensolver_complex_2 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_complex_3 "eigensolver_complex_3")
SET_TESTS_PROPERTIES(eigensolver_complex_3 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_complex_4 "eigensolver_complex_4")
SET_TESTS_PROPERTIES(eigensolver_complex_4 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_complex_5 "eigensolver_complex_5")
SET_TESTS_PROPERTIES(eigensolver_complex_5 PROPERTIES  LABELS "Official")
ADD_TEST(real_qz_1 "real_qz_1")
SET_TESTS_PROPERTIES(real_qz_1 PROPERTIES  LABELS "Official")
ADD_TEST(real_qz_2 "real_qz_2")
SET_TESTS_PROPERTIES(real_qz_2 PROPERTIES  LABELS "Official")
ADD_TEST(real_qz_3 "real_qz_3")
SET_TESTS_PROPERTIES(real_qz_3 PROPERTIES  LABELS "Official")
ADD_TEST(real_qz_4 "real_qz_4")
SET_TESTS_PROPERTIES(real_qz_4 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generalized_real_1 "eigensolver_generalized_real_1")
SET_TESTS_PROPERTIES(eigensolver_generalized_real_1 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generalized_real_2 "eigensolver_generalized_real_2")
SET_TESTS_PROPERTIES(eigensolver_generalized_real_2 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generalized_real_3 "eigensolver_generalized_real_3")
SET_TESTS_PROPERTIES(eigensolver_generalized_real_3 PROPERTIES  LABELS "Official")
ADD_TEST(eigensolver_generalized_real_4 "eigensolver_generalized_real_4")
SET_TESTS_PROPERTIES(eigensolver_generalized_real_4 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_1 "jacobi_1")
SET_TESTS_PROPERTIES(jacobi_1 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_2 "jacobi_2")
SET_TESTS_PROPERTIES(jacobi_2 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_3 "jacobi_3")
SET_TESTS_PROPERTIES(jacobi_3 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_4 "jacobi_4")
SET_TESTS_PROPERTIES(jacobi_4 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_5 "jacobi_5")
SET_TESTS_PROPERTIES(jacobi_5 PROPERTIES  LABELS "Official")
ADD_TEST(jacobi_6 "jacobi_6")
SET_TESTS_PROPERTIES(jacobi_6 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_3 "jacobisvd_3")
SET_TESTS_PROPERTIES(jacobisvd_3 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_4 "jacobisvd_4")
SET_TESTS_PROPERTIES(jacobisvd_4 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_7 "jacobisvd_7")
SET_TESTS_PROPERTIES(jacobisvd_7 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_8 "jacobisvd_8")
SET_TESTS_PROPERTIES(jacobisvd_8 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_11 "jacobisvd_11")
SET_TESTS_PROPERTIES(jacobisvd_11 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_12 "jacobisvd_12")
SET_TESTS_PROPERTIES(jacobisvd_12 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_5 "jacobisvd_5")
SET_TESTS_PROPERTIES(jacobisvd_5 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_6 "jacobisvd_6")
SET_TESTS_PROPERTIES(jacobisvd_6 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_10 "jacobisvd_10")
SET_TESTS_PROPERTIES(jacobisvd_10 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_13 "jacobisvd_13")
SET_TESTS_PROPERTIES(jacobisvd_13 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_1 "jacobisvd_1")
SET_TESTS_PROPERTIES(jacobisvd_1 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_9 "jacobisvd_9")
SET_TESTS_PROPERTIES(jacobisvd_9 PROPERTIES  LABELS "Official")
ADD_TEST(jacobisvd_2 "jacobisvd_2")
SET_TESTS_PROPERTIES(jacobisvd_2 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_3 "bdcsvd_3")
SET_TESTS_PROPERTIES(bdcsvd_3 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_4 "bdcsvd_4")
SET_TESTS_PROPERTIES(bdcsvd_4 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_7 "bdcsvd_7")
SET_TESTS_PROPERTIES(bdcsvd_7 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_8 "bdcsvd_8")
SET_TESTS_PROPERTIES(bdcsvd_8 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_101 "bdcsvd_101")
SET_TESTS_PROPERTIES(bdcsvd_101 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_102 "bdcsvd_102")
SET_TESTS_PROPERTIES(bdcsvd_102 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_5 "bdcsvd_5")
SET_TESTS_PROPERTIES(bdcsvd_5 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_6 "bdcsvd_6")
SET_TESTS_PROPERTIES(bdcsvd_6 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_10 "bdcsvd_10")
SET_TESTS_PROPERTIES(bdcsvd_10 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_1 "bdcsvd_1")
SET_TESTS_PROPERTIES(bdcsvd_1 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_9 "bdcsvd_9")
SET_TESTS_PROPERTIES(bdcsvd_9 PROPERTIES  LABELS "Official")
ADD_TEST(bdcsvd_2 "bdcsvd_2")
SET_TESTS_PROPERTIES(bdcsvd_2 PROPERTIES  LABELS "Official")
ADD_TEST(householder_1 "householder_1")
SET_TESTS_PROPERTIES(householder_1 PROPERTIES  LABELS "Official")
ADD_TEST(householder_2 "householder_2")
SET_TESTS_PROPERTIES(householder_2 PROPERTIES  LABELS "Official")
ADD_TEST(householder_3 "householder_3")
SET_TESTS_PROPERTIES(householder_3 PROPERTIES  LABELS "Official")
ADD_TEST(householder_4 "householder_4")
SET_TESTS_PROPERTIES(householder_4 PROPERTIES  LABELS "Official")
ADD_TEST(householder_5 "householder_5")
SET_TESTS_PROPERTIES(householder_5 PROPERTIES  LABELS "Official")
ADD_TEST(householder_6 "householder_6")
SET_TESTS_PROPERTIES(householder_6 PROPERTIES  LABELS "Official")
ADD_TEST(householder_7 "householder_7")
SET_TESTS_PROPERTIES(householder_7 PROPERTIES  LABELS "Official")
ADD_TEST(householder_8 "householder_8")
SET_TESTS_PROPERTIES(householder_8 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_1 "geo_orthomethods_1")
SET_TESTS_PROPERTIES(geo_orthomethods_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_2 "geo_orthomethods_2")
SET_TESTS_PROPERTIES(geo_orthomethods_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_4 "geo_orthomethods_4")
SET_TESTS_PROPERTIES(geo_orthomethods_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_3 "geo_orthomethods_3")
SET_TESTS_PROPERTIES(geo_orthomethods_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_5 "geo_orthomethods_5")
SET_TESTS_PROPERTIES(geo_orthomethods_5 PROPERTIES  LABELS "Official")
ADD_TEST(geo_orthomethods_6 "geo_orthomethods_6")
SET_TESTS_PROPERTIES(geo_orthomethods_6 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_1 "geo_quaternion_1")
SET_TESTS_PROPERTIES(geo_quaternion_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_2 "geo_quaternion_2")
SET_TESTS_PROPERTIES(geo_quaternion_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_3 "geo_quaternion_3")
SET_TESTS_PROPERTIES(geo_quaternion_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_4 "geo_quaternion_4")
SET_TESTS_PROPERTIES(geo_quaternion_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_5 "geo_quaternion_5")
SET_TESTS_PROPERTIES(geo_quaternion_5 PROPERTIES  LABELS "Official")
ADD_TEST(geo_quaternion_6 "geo_quaternion_6")
SET_TESTS_PROPERTIES(geo_quaternion_6 PROPERTIES  LABELS "Official")
ADD_TEST(geo_eulerangles_1 "geo_eulerangles_1")
SET_TESTS_PROPERTIES(geo_eulerangles_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_eulerangles_2 "geo_eulerangles_2")
SET_TESTS_PROPERTIES(geo_eulerangles_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_parametrizedline_1 "geo_parametrizedline_1")
SET_TESTS_PROPERTIES(geo_parametrizedline_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_parametrizedline_2 "geo_parametrizedline_2")
SET_TESTS_PROPERTIES(geo_parametrizedline_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_parametrizedline_3 "geo_parametrizedline_3")
SET_TESTS_PROPERTIES(geo_parametrizedline_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_parametrizedline_4 "geo_parametrizedline_4")
SET_TESTS_PROPERTIES(geo_parametrizedline_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_1 "geo_alignedbox_1")
SET_TESTS_PROPERTIES(geo_alignedbox_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_2 "geo_alignedbox_2")
SET_TESTS_PROPERTIES(geo_alignedbox_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_3 "geo_alignedbox_3")
SET_TESTS_PROPERTIES(geo_alignedbox_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_4 "geo_alignedbox_4")
SET_TESTS_PROPERTIES(geo_alignedbox_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_5 "geo_alignedbox_5")
SET_TESTS_PROPERTIES(geo_alignedbox_5 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_6 "geo_alignedbox_6")
SET_TESTS_PROPERTIES(geo_alignedbox_6 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_7 "geo_alignedbox_7")
SET_TESTS_PROPERTIES(geo_alignedbox_7 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_8 "geo_alignedbox_8")
SET_TESTS_PROPERTIES(geo_alignedbox_8 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_9 "geo_alignedbox_9")
SET_TESTS_PROPERTIES(geo_alignedbox_9 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_10 "geo_alignedbox_10")
SET_TESTS_PROPERTIES(geo_alignedbox_10 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_11 "geo_alignedbox_11")
SET_TESTS_PROPERTIES(geo_alignedbox_11 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_14 "geo_alignedbox_14")
SET_TESTS_PROPERTIES(geo_alignedbox_14 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_12 "geo_alignedbox_12")
SET_TESTS_PROPERTIES(geo_alignedbox_12 PROPERTIES  LABELS "Official")
ADD_TEST(geo_alignedbox_13 "geo_alignedbox_13")
SET_TESTS_PROPERTIES(geo_alignedbox_13 PROPERTIES  LABELS "Official")
ADD_TEST(geo_hyperplane_1 "geo_hyperplane_1")
SET_TESTS_PROPERTIES(geo_hyperplane_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_hyperplane_2 "geo_hyperplane_2")
SET_TESTS_PROPERTIES(geo_hyperplane_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_hyperplane_3 "geo_hyperplane_3")
SET_TESTS_PROPERTIES(geo_hyperplane_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_hyperplane_4 "geo_hyperplane_4")
SET_TESTS_PROPERTIES(geo_hyperplane_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_hyperplane_5 "geo_hyperplane_5")
SET_TESTS_PROPERTIES(geo_hyperplane_5 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_1 "geo_transformations_1")
SET_TESTS_PROPERTIES(geo_transformations_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_2 "geo_transformations_2")
SET_TESTS_PROPERTIES(geo_transformations_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_3 "geo_transformations_3")
SET_TESTS_PROPERTIES(geo_transformations_3 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_4 "geo_transformations_4")
SET_TESTS_PROPERTIES(geo_transformations_4 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_5 "geo_transformations_5")
SET_TESTS_PROPERTIES(geo_transformations_5 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_6 "geo_transformations_6")
SET_TESTS_PROPERTIES(geo_transformations_6 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_7 "geo_transformations_7")
SET_TESTS_PROPERTIES(geo_transformations_7 PROPERTIES  LABELS "Official")
ADD_TEST(geo_transformations_8 "geo_transformations_8")
SET_TESTS_PROPERTIES(geo_transformations_8 PROPERTIES  LABELS "Official")
ADD_TEST(geo_homogeneous_1 "geo_homogeneous_1")
SET_TESTS_PROPERTIES(geo_homogeneous_1 PROPERTIES  LABELS "Official")
ADD_TEST(geo_homogeneous_2 "geo_homogeneous_2")
SET_TESTS_PROPERTIES(geo_homogeneous_2 PROPERTIES  LABELS "Official")
ADD_TEST(geo_homogeneous_3 "geo_homogeneous_3")
SET_TESTS_PROPERTIES(geo_homogeneous_3 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_1 "stdvector_1")
SET_TESTS_PROPERTIES(stdvector_1 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_2 "stdvector_2")
SET_TESTS_PROPERTIES(stdvector_2 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_3 "stdvector_3")
SET_TESTS_PROPERTIES(stdvector_3 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_4 "stdvector_4")
SET_TESTS_PROPERTIES(stdvector_4 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_5 "stdvector_5")
SET_TESTS_PROPERTIES(stdvector_5 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_overload_1 "stdvector_overload_1")
SET_TESTS_PROPERTIES(stdvector_overload_1 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_overload_2 "stdvector_overload_2")
SET_TESTS_PROPERTIES(stdvector_overload_2 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_overload_3 "stdvector_overload_3")
SET_TESTS_PROPERTIES(stdvector_overload_3 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_overload_4 "stdvector_overload_4")
SET_TESTS_PROPERTIES(stdvector_overload_4 PROPERTIES  LABELS "Official")
ADD_TEST(stdvector_overload_5 "stdvector_overload_5")
SET_TESTS_PROPERTIES(stdvector_overload_5 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_1 "stdlist_1")
SET_TESTS_PROPERTIES(stdlist_1 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_2 "stdlist_2")
SET_TESTS_PROPERTIES(stdlist_2 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_3 "stdlist_3")
SET_TESTS_PROPERTIES(stdlist_3 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_4 "stdlist_4")
SET_TESTS_PROPERTIES(stdlist_4 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_5 "stdlist_5")
SET_TESTS_PROPERTIES(stdlist_5 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_overload_1 "stdlist_overload_1")
SET_TESTS_PROPERTIES(stdlist_overload_1 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_overload_2 "stdlist_overload_2")
SET_TESTS_PROPERTIES(stdlist_overload_2 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_overload_3 "stdlist_overload_3")
SET_TESTS_PROPERTIES(stdlist_overload_3 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_overload_4 "stdlist_overload_4")
SET_TESTS_PROPERTIES(stdlist_overload_4 PROPERTIES  LABELS "Official")
ADD_TEST(stdlist_overload_5 "stdlist_overload_5")
SET_TESTS_PROPERTIES(stdlist_overload_5 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_1 "stddeque_1")
SET_TESTS_PROPERTIES(stddeque_1 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_2 "stddeque_2")
SET_TESTS_PROPERTIES(stddeque_2 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_3 "stddeque_3")
SET_TESTS_PROPERTIES(stddeque_3 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_4 "stddeque_4")
SET_TESTS_PROPERTIES(stddeque_4 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_5 "stddeque_5")
SET_TESTS_PROPERTIES(stddeque_5 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_overload_1 "stddeque_overload_1")
SET_TESTS_PROPERTIES(stddeque_overload_1 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_overload_2 "stddeque_overload_2")
SET_TESTS_PROPERTIES(stddeque_overload_2 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_overload_3 "stddeque_overload_3")
SET_TESTS_PROPERTIES(stddeque_overload_3 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_overload_4 "stddeque_overload_4")
SET_TESTS_PROPERTIES(stddeque_overload_4 PROPERTIES  LABELS "Official")
ADD_TEST(stddeque_overload_5 "stddeque_overload_5")
SET_TESTS_PROPERTIES(stddeque_overload_5 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_1 "sparse_basic_1")
SET_TESTS_PROPERTIES(sparse_basic_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_2 "sparse_basic_2")
SET_TESTS_PROPERTIES(sparse_basic_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_5 "sparse_basic_5")
SET_TESTS_PROPERTIES(sparse_basic_5 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_6 "sparse_basic_6")
SET_TESTS_PROPERTIES(sparse_basic_6 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_3 "sparse_basic_3")
SET_TESTS_PROPERTIES(sparse_basic_3 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_4 "sparse_basic_4")
SET_TESTS_PROPERTIES(sparse_basic_4 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_basic_7 "sparse_basic_7")
SET_TESTS_PROPERTIES(sparse_basic_7 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_block_1 "sparse_block_1")
SET_TESTS_PROPERTIES(sparse_block_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_block_2 "sparse_block_2")
SET_TESTS_PROPERTIES(sparse_block_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_block_3 "sparse_block_3")
SET_TESTS_PROPERTIES(sparse_block_3 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_block_4 "sparse_block_4")
SET_TESTS_PROPERTIES(sparse_block_4 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_vector_1 "sparse_vector_1")
SET_TESTS_PROPERTIES(sparse_vector_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_vector_2 "sparse_vector_2")
SET_TESTS_PROPERTIES(sparse_vector_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_product_1 "sparse_product_1")
SET_TESTS_PROPERTIES(sparse_product_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_product_2 "sparse_product_2")
SET_TESTS_PROPERTIES(sparse_product_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_product_3 "sparse_product_3")
SET_TESTS_PROPERTIES(sparse_product_3 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_product_4 "sparse_product_4")
SET_TESTS_PROPERTIES(sparse_product_4 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_ref_1 "sparse_ref_1")
SET_TESTS_PROPERTIES(sparse_ref_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_ref_2 "sparse_ref_2")
SET_TESTS_PROPERTIES(sparse_ref_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_ref_3 "sparse_ref_3")
SET_TESTS_PROPERTIES(sparse_ref_3 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_solvers_1 "sparse_solvers_1")
SET_TESTS_PROPERTIES(sparse_solvers_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_solvers_2 "sparse_solvers_2")
SET_TESTS_PROPERTIES(sparse_solvers_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_permutations_1 "sparse_permutations_1")
SET_TESTS_PROPERTIES(sparse_permutations_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparse_permutations_2 "sparse_permutations_2")
SET_TESTS_PROPERTIES(sparse_permutations_2 PROPERTIES  LABELS "Official")
ADD_TEST(simplicial_cholesky_1 "simplicial_cholesky_1")
SET_TESTS_PROPERTIES(simplicial_cholesky_1 PROPERTIES  LABELS "Official")
ADD_TEST(simplicial_cholesky_2 "simplicial_cholesky_2")
SET_TESTS_PROPERTIES(simplicial_cholesky_2 PROPERTIES  LABELS "Official")
ADD_TEST(simplicial_cholesky_3 "simplicial_cholesky_3")
SET_TESTS_PROPERTIES(simplicial_cholesky_3 PROPERTIES  LABELS "Official")
ADD_TEST(conjugate_gradient_1 "conjugate_gradient_1")
SET_TESTS_PROPERTIES(conjugate_gradient_1 PROPERTIES  LABELS "Official")
ADD_TEST(conjugate_gradient_2 "conjugate_gradient_2")
SET_TESTS_PROPERTIES(conjugate_gradient_2 PROPERTIES  LABELS "Official")
ADD_TEST(conjugate_gradient_3 "conjugate_gradient_3")
SET_TESTS_PROPERTIES(conjugate_gradient_3 PROPERTIES  LABELS "Official")
ADD_TEST(incomplete_cholesky_1 "incomplete_cholesky_1")
SET_TESTS_PROPERTIES(incomplete_cholesky_1 PROPERTIES  LABELS "Official")
ADD_TEST(incomplete_cholesky_2 "incomplete_cholesky_2")
SET_TESTS_PROPERTIES(incomplete_cholesky_2 PROPERTIES  LABELS "Official")
ADD_TEST(incomplete_cholesky_3 "incomplete_cholesky_3")
SET_TESTS_PROPERTIES(incomplete_cholesky_3 PROPERTIES  LABELS "Official")
ADD_TEST(bicgstab_1 "bicgstab_1")
SET_TESTS_PROPERTIES(bicgstab_1 PROPERTIES  LABELS "Official")
ADD_TEST(bicgstab_2 "bicgstab_2")
SET_TESTS_PROPERTIES(bicgstab_2 PROPERTIES  LABELS "Official")
ADD_TEST(bicgstab_3 "bicgstab_3")
SET_TESTS_PROPERTIES(bicgstab_3 PROPERTIES  LABELS "Official")
ADD_TEST(lscg_1 "lscg_1")
SET_TESTS_PROPERTIES(lscg_1 PROPERTIES  LABELS "Official")
ADD_TEST(lscg_2 "lscg_2")
SET_TESTS_PROPERTIES(lscg_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparselu_1 "sparselu_1")
SET_TESTS_PROPERTIES(sparselu_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparselu_2 "sparselu_2")
SET_TESTS_PROPERTIES(sparselu_2 PROPERTIES  LABELS "Official")
ADD_TEST(sparselu_3 "sparselu_3")
SET_TESTS_PROPERTIES(sparselu_3 PROPERTIES  LABELS "Official")
ADD_TEST(sparselu_4 "sparselu_4")
SET_TESTS_PROPERTIES(sparselu_4 PROPERTIES  LABELS "Official")
ADD_TEST(sparseqr_1 "sparseqr_1")
SET_TESTS_PROPERTIES(sparseqr_1 PROPERTIES  LABELS "Official")
ADD_TEST(sparseqr_2 "sparseqr_2")
SET_TESTS_PROPERTIES(sparseqr_2 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_1 "umeyama_1")
SET_TESTS_PROPERTIES(umeyama_1 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_2 "umeyama_2")
SET_TESTS_PROPERTIES(umeyama_2 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_3 "umeyama_3")
SET_TESTS_PROPERTIES(umeyama_3 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_4 "umeyama_4")
SET_TESTS_PROPERTIES(umeyama_4 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_5 "umeyama_5")
SET_TESTS_PROPERTIES(umeyama_5 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_6 "umeyama_6")
SET_TESTS_PROPERTIES(umeyama_6 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_7 "umeyama_7")
SET_TESTS_PROPERTIES(umeyama_7 PROPERTIES  LABELS "Official")
ADD_TEST(umeyama_8 "umeyama_8")
SET_TESTS_PROPERTIES(umeyama_8 PROPERTIES  LABELS "Official")
ADD_TEST(nesting_ops_1 "nesting_ops_1")
SET_TESTS_PROPERTIES(nesting_ops_1 PROPERTIES  LABELS "Official")
ADD_TEST(nesting_ops_2 "nesting_ops_2")
SET_TESTS_PROPERTIES(nesting_ops_2 PROPERTIES  LABELS "Official")
ADD_TEST(nesting_ops_3 "nesting_ops_3")
SET_TESTS_PROPERTIES(nesting_ops_3 PROPERTIES  LABELS "Official")
ADD_TEST(nesting_ops_4 "nesting_ops_4")
SET_TESTS_PROPERTIES(nesting_ops_4 PROPERTIES  LABELS "Official")
ADD_TEST(zerosized "zerosized")
SET_TESTS_PROPERTIES(zerosized PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_1 "dontalign_1")
SET_TESTS_PROPERTIES(dontalign_1 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_2 "dontalign_2")
SET_TESTS_PROPERTIES(dontalign_2 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_3 "dontalign_3")
SET_TESTS_PROPERTIES(dontalign_3 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_4 "dontalign_4")
SET_TESTS_PROPERTIES(dontalign_4 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_5 "dontalign_5")
SET_TESTS_PROPERTIES(dontalign_5 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_6 "dontalign_6")
SET_TESTS_PROPERTIES(dontalign_6 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_7 "dontalign_7")
SET_TESTS_PROPERTIES(dontalign_7 PROPERTIES  LABELS "Official")
ADD_TEST(dontalign_8 "dontalign_8")
SET_TESTS_PROPERTIES(dontalign_8 PROPERTIES  LABELS "Official")
ADD_TEST(evaluators "evaluators")
SET_TESTS_PROPERTIES(evaluators PROPERTIES  LABELS "Official")
ADD_TEST(sizeoverflow "sizeoverflow")
SET_TESTS_PROPERTIES(sizeoverflow PROPERTIES  LABELS "Official")
ADD_TEST(prec_inverse_4x4_1 "prec_inverse_4x4_1")
SET_TESTS_PROPERTIES(prec_inverse_4x4_1 PROPERTIES  LABELS "Official")
ADD_TEST(prec_inverse_4x4_2 "prec_inverse_4x4_2")
SET_TESTS_PROPERTIES(prec_inverse_4x4_2 PROPERTIES  LABELS "Official")
ADD_TEST(prec_inverse_4x4_3 "prec_inverse_4x4_3")
SET_TESTS_PROPERTIES(prec_inverse_4x4_3 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_1 "vectorwiseop_1")
SET_TESTS_PROPERTIES(vectorwiseop_1 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_2 "vectorwiseop_2")
SET_TESTS_PROPERTIES(vectorwiseop_2 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_3 "vectorwiseop_3")
SET_TESTS_PROPERTIES(vectorwiseop_3 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_4 "vectorwiseop_4")
SET_TESTS_PROPERTIES(vectorwiseop_4 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_5 "vectorwiseop_5")
SET_TESTS_PROPERTIES(vectorwiseop_5 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_6 "vectorwiseop_6")
SET_TESTS_PROPERTIES(vectorwiseop_6 PROPERTIES  LABELS "Official")
ADD_TEST(vectorwiseop_7 "vectorwiseop_7")
SET_TESTS_PROPERTIES(vectorwiseop_7 PROPERTIES  LABELS "Official")
ADD_TEST(special_numbers_1 "special_numbers_1")
SET_TESTS_PROPERTIES(special_numbers_1 PROPERTIES  LABELS "Official")
ADD_TEST(rvalue_types_1 "rvalue_types_1")
SET_TESTS_PROPERTIES(rvalue_types_1 PROPERTIES  LABELS "Official")
ADD_TEST(rvalue_types_2 "rvalue_types_2")
SET_TESTS_PROPERTIES(rvalue_types_2 PROPERTIES  LABELS "Official")
ADD_TEST(dense_storage "dense_storage")
SET_TESTS_PROPERTIES(dense_storage PROPERTIES  LABELS "Official")
ADD_TEST(ctorleak "ctorleak")
SET_TESTS_PROPERTIES(ctorleak PROPERTIES  LABELS "Official")
ADD_TEST(mpl2only "mpl2only")
SET_TESTS_PROPERTIES(mpl2only PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_1 "inplace_decomposition_1")
SET_TESTS_PROPERTIES(inplace_decomposition_1 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_2 "inplace_decomposition_2")
SET_TESTS_PROPERTIES(inplace_decomposition_2 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_3 "inplace_decomposition_3")
SET_TESTS_PROPERTIES(inplace_decomposition_3 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_4 "inplace_decomposition_4")
SET_TESTS_PROPERTIES(inplace_decomposition_4 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_5 "inplace_decomposition_5")
SET_TESTS_PROPERTIES(inplace_decomposition_5 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_6 "inplace_decomposition_6")
SET_TESTS_PROPERTIES(inplace_decomposition_6 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_7 "inplace_decomposition_7")
SET_TESTS_PROPERTIES(inplace_decomposition_7 PROPERTIES  LABELS "Official")
ADD_TEST(inplace_decomposition_8 "inplace_decomposition_8")
SET_TESTS_PROPERTIES(inplace_decomposition_8 PROPERTIES  LABELS "Official")
ADD_TEST(half_float "half_float")
SET_TESTS_PROPERTIES(half_float PROPERTIES  LABELS "Official")
ADD_TEST(array_of_string "array_of_string")
SET_TESTS_PROPERTIES(array_of_string PROPERTIES  LABELS "Official")
ADD_TEST(fastmath "fastmath")
SET_TESTS_PROPERTIES(fastmath PROPERTIES  LABELS "Official")
ADD_TEST(qtvector "qtvector")
SET_TESTS_PROPERTIES(qtvector PROPERTIES  LABELS "Official")
ADD_TEST(umfpack_support_1 "umfpack_support_1")
SET_TESTS_PROPERTIES(umfpack_support_1 PROPERTIES  LABELS "Official")
ADD_TEST(umfpack_support_2 "umfpack_support_2")
SET_TESTS_PROPERTIES(umfpack_support_2 PROPERTIES  LABELS "Official")
ADD_TEST(cholmod_support_1 "cholmod_support_1")
SET_TESTS_PROPERTIES(cholmod_support_1 PROPERTIES  LABELS "Official")
ADD_TEST(cholmod_support_2 "cholmod_support_2")
SET_TESTS_PROPERTIES(cholmod_support_2 PROPERTIES  LABELS "Official")
ADD_TEST(spqr_support_1 "spqr_support_1")
SET_TESTS_PROPERTIES(spqr_support_1 PROPERTIES  LABELS "Official")
ADD_TEST(spqr_support_2 "spqr_support_2")
SET_TESTS_PROPERTIES(spqr_support_2 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_1 "boostmultiprec_1")
SET_TESTS_PROPERTIES(boostmultiprec_1 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_2 "boostmultiprec_2")
SET_TESTS_PROPERTIES(boostmultiprec_2 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_3 "boostmultiprec_3")
SET_TESTS_PROPERTIES(boostmultiprec_3 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_4 "boostmultiprec_4")
SET_TESTS_PROPERTIES(boostmultiprec_4 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_5 "boostmultiprec_5")
SET_TESTS_PROPERTIES(boostmultiprec_5 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_6 "boostmultiprec_6")
SET_TESTS_PROPERTIES(boostmultiprec_6 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_7 "boostmultiprec_7")
SET_TESTS_PROPERTIES(boostmultiprec_7 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_8 "boostmultiprec_8")
SET_TESTS_PROPERTIES(boostmultiprec_8 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_9 "boostmultiprec_9")
SET_TESTS_PROPERTIES(boostmultiprec_9 PROPERTIES  LABELS "Official")
ADD_TEST(boostmultiprec_10 "boostmultiprec_10")
SET_TESTS_PROPERTIES(boostmultiprec_10 PROPERTIES  LABELS "Official")
ADD_TEST(failtests "/usr/bin/cmake" "/home/chenrui/catkin_ws/src/build_dir/source_dir" "-G" "Unix Makefiles" "-DEIGEN_FAILTEST=ON")
SET_TESTS_PROPERTIES(failtests PROPERTIES  WORKING_DIRECTORY "/home/chenrui/catkin_ws/src/build_dir/test/failtests")
