# CMake generated Testfile for 
# Source directory: /home/chenrui/catkin_ws/src/build_dir/source_dir/unsupported/test
# Build directory: /home/chenrui/catkin_ws/src/build_dir/unsupported/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(NonLinearOptimization "NonLinearOptimization")
SET_TESTS_PROPERTIES(NonLinearOptimization PROPERTIES  LABELS "Unsupported")
ADD_TEST(NumericalDiff "NumericalDiff")
SET_TESTS_PROPERTIES(NumericalDiff PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_scalar_1 "autodiff_scalar_1")
SET_TESTS_PROPERTIES(autodiff_scalar_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_scalar_2 "autodiff_scalar_2")
SET_TESTS_PROPERTIES(autodiff_scalar_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_scalar_3 "autodiff_scalar_3")
SET_TESTS_PROPERTIES(autodiff_scalar_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_scalar_4 "autodiff_scalar_4")
SET_TESTS_PROPERTIES(autodiff_scalar_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_1 "autodiff_1")
SET_TESTS_PROPERTIES(autodiff_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_2 "autodiff_2")
SET_TESTS_PROPERTIES(autodiff_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_3 "autodiff_3")
SET_TESTS_PROPERTIES(autodiff_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(autodiff_4 "autodiff_4")
SET_TESTS_PROPERTIES(autodiff_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(BVH_1 "BVH_1")
SET_TESTS_PROPERTIES(BVH_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(BVH_2 "BVH_2")
SET_TESTS_PROPERTIES(BVH_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(BVH_3 "BVH_3")
SET_TESTS_PROPERTIES(BVH_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_2 "matrix_exponential_2")
SET_TESTS_PROPERTIES(matrix_exponential_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_1 "matrix_exponential_1")
SET_TESTS_PROPERTIES(matrix_exponential_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_8 "matrix_exponential_8")
SET_TESTS_PROPERTIES(matrix_exponential_8 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_6 "matrix_exponential_6")
SET_TESTS_PROPERTIES(matrix_exponential_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_5 "matrix_exponential_5")
SET_TESTS_PROPERTIES(matrix_exponential_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_7 "matrix_exponential_7")
SET_TESTS_PROPERTIES(matrix_exponential_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_3 "matrix_exponential_3")
SET_TESTS_PROPERTIES(matrix_exponential_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_4 "matrix_exponential_4")
SET_TESTS_PROPERTIES(matrix_exponential_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_exponential_9 "matrix_exponential_9")
SET_TESTS_PROPERTIES(matrix_exponential_9 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_1 "matrix_function_1")
SET_TESTS_PROPERTIES(matrix_function_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_2 "matrix_function_2")
SET_TESTS_PROPERTIES(matrix_function_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_3 "matrix_function_3")
SET_TESTS_PROPERTIES(matrix_function_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_4 "matrix_function_4")
SET_TESTS_PROPERTIES(matrix_function_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_5 "matrix_function_5")
SET_TESTS_PROPERTIES(matrix_function_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_6 "matrix_function_6")
SET_TESTS_PROPERTIES(matrix_function_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_function_7 "matrix_function_7")
SET_TESTS_PROPERTIES(matrix_function_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_2 "matrix_power_2")
SET_TESTS_PROPERTIES(matrix_power_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_1 "matrix_power_1")
SET_TESTS_PROPERTIES(matrix_power_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_9 "matrix_power_9")
SET_TESTS_PROPERTIES(matrix_power_9 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_10 "matrix_power_10")
SET_TESTS_PROPERTIES(matrix_power_10 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_11 "matrix_power_11")
SET_TESTS_PROPERTIES(matrix_power_11 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_12 "matrix_power_12")
SET_TESTS_PROPERTIES(matrix_power_12 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_7 "matrix_power_7")
SET_TESTS_PROPERTIES(matrix_power_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_3 "matrix_power_3")
SET_TESTS_PROPERTIES(matrix_power_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_4 "matrix_power_4")
SET_TESTS_PROPERTIES(matrix_power_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_5 "matrix_power_5")
SET_TESTS_PROPERTIES(matrix_power_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_8 "matrix_power_8")
SET_TESTS_PROPERTIES(matrix_power_8 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_power_6 "matrix_power_6")
SET_TESTS_PROPERTIES(matrix_power_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_square_root_1 "matrix_square_root_1")
SET_TESTS_PROPERTIES(matrix_square_root_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_square_root_2 "matrix_square_root_2")
SET_TESTS_PROPERTIES(matrix_square_root_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_square_root_3 "matrix_square_root_3")
SET_TESTS_PROPERTIES(matrix_square_root_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_square_root_4 "matrix_square_root_4")
SET_TESTS_PROPERTIES(matrix_square_root_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(matrix_square_root_5 "matrix_square_root_5")
SET_TESTS_PROPERTIES(matrix_square_root_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(alignedvector3 "alignedvector3")
SET_TESTS_PROPERTIES(alignedvector3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(FFT "FFT")
SET_TESTS_PROPERTIES(FFT PROPERTIES  LABELS "Unsupported")
ADD_TEST(EulerAngles_1 "EulerAngles_1")
SET_TESTS_PROPERTIES(EulerAngles_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(EulerAngles_2 "EulerAngles_2")
SET_TESTS_PROPERTIES(EulerAngles_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(sparse_extra_1 "sparse_extra_1")
SET_TESTS_PROPERTIES(sparse_extra_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(sparse_extra_2 "sparse_extra_2")
SET_TESTS_PROPERTIES(sparse_extra_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(sparse_extra_3 "sparse_extra_3")
SET_TESTS_PROPERTIES(sparse_extra_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_1 "polynomialsolver_1")
SET_TESTS_PROPERTIES(polynomialsolver_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_2 "polynomialsolver_2")
SET_TESTS_PROPERTIES(polynomialsolver_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_3 "polynomialsolver_3")
SET_TESTS_PROPERTIES(polynomialsolver_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_4 "polynomialsolver_4")
SET_TESTS_PROPERTIES(polynomialsolver_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_5 "polynomialsolver_5")
SET_TESTS_PROPERTIES(polynomialsolver_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_6 "polynomialsolver_6")
SET_TESTS_PROPERTIES(polynomialsolver_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_7 "polynomialsolver_7")
SET_TESTS_PROPERTIES(polynomialsolver_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_8 "polynomialsolver_8")
SET_TESTS_PROPERTIES(polynomialsolver_8 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_9 "polynomialsolver_9")
SET_TESTS_PROPERTIES(polynomialsolver_9 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_10 "polynomialsolver_10")
SET_TESTS_PROPERTIES(polynomialsolver_10 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialsolver_11 "polynomialsolver_11")
SET_TESTS_PROPERTIES(polynomialsolver_11 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_2 "polynomialutils_2")
SET_TESTS_PROPERTIES(polynomialutils_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_3 "polynomialutils_3")
SET_TESTS_PROPERTIES(polynomialutils_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_4 "polynomialutils_4")
SET_TESTS_PROPERTIES(polynomialutils_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_5 "polynomialutils_5")
SET_TESTS_PROPERTIES(polynomialutils_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_6 "polynomialutils_6")
SET_TESTS_PROPERTIES(polynomialutils_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_7 "polynomialutils_7")
SET_TESTS_PROPERTIES(polynomialutils_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_8 "polynomialutils_8")
SET_TESTS_PROPERTIES(polynomialutils_8 PROPERTIES  LABELS "Unsupported")
ADD_TEST(polynomialutils_9 "polynomialutils_9")
SET_TESTS_PROPERTIES(polynomialutils_9 PROPERTIES  LABELS "Unsupported")
ADD_TEST(splines "splines")
SET_TESTS_PROPERTIES(splines PROPERTIES  LABELS "Unsupported")
ADD_TEST(gmres_1 "gmres_1")
SET_TESTS_PROPERTIES(gmres_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(gmres_2 "gmres_2")
SET_TESTS_PROPERTIES(gmres_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(minres_1 "minres_1")
SET_TESTS_PROPERTIES(minres_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(minres_2 "minres_2")
SET_TESTS_PROPERTIES(minres_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(levenberg_marquardt "levenberg_marquardt")
SET_TESTS_PROPERTIES(levenberg_marquardt PROPERTIES  LABELS "Unsupported")
ADD_TEST(kronecker_product_1 "kronecker_product_1")
SET_TESTS_PROPERTIES(kronecker_product_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(kronecker_product_2 "kronecker_product_2")
SET_TESTS_PROPERTIES(kronecker_product_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(special_functions_1 "special_functions_1")
SET_TESTS_PROPERTIES(special_functions_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(special_functions_2 "special_functions_2")
SET_TESTS_PROPERTIES(special_functions_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_dimension "cxx11_tensor_dimension")
SET_TESTS_PROPERTIES(cxx11_tensor_dimension PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_map "cxx11_tensor_map")
SET_TESTS_PROPERTIES(cxx11_tensor_map PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_assign "cxx11_tensor_assign")
SET_TESTS_PROPERTIES(cxx11_tensor_assign PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_comparisons "cxx11_tensor_comparisons")
SET_TESTS_PROPERTIES(cxx11_tensor_comparisons PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_forced_eval "cxx11_tensor_forced_eval")
SET_TESTS_PROPERTIES(cxx11_tensor_forced_eval PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_math "cxx11_tensor_math")
SET_TESTS_PROPERTIES(cxx11_tensor_math PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_const "cxx11_tensor_const")
SET_TESTS_PROPERTIES(cxx11_tensor_const PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_1 "cxx11_tensor_intdiv_1")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_2 "cxx11_tensor_intdiv_2")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_3 "cxx11_tensor_intdiv_3")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_4 "cxx11_tensor_intdiv_4")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_5 "cxx11_tensor_intdiv_5")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_6 "cxx11_tensor_intdiv_6")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_6 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_intdiv_7 "cxx11_tensor_intdiv_7")
SET_TESTS_PROPERTIES(cxx11_tensor_intdiv_7 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_casts "cxx11_tensor_casts")
SET_TESTS_PROPERTIES(cxx11_tensor_casts PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_empty "cxx11_tensor_empty")
SET_TESTS_PROPERTIES(cxx11_tensor_empty PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_sugar "cxx11_tensor_sugar")
SET_TESTS_PROPERTIES(cxx11_tensor_sugar PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_roundings "cxx11_tensor_roundings")
SET_TESTS_PROPERTIES(cxx11_tensor_roundings PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_layout_swap "cxx11_tensor_layout_swap")
SET_TESTS_PROPERTIES(cxx11_tensor_layout_swap PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_io "cxx11_tensor_io")
SET_TESTS_PROPERTIES(cxx11_tensor_io PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_1 "cxx11_tensor_uint128_1")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_1 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_2 "cxx11_tensor_uint128_2")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_2 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_3 "cxx11_tensor_uint128_3")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_3 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_4 "cxx11_tensor_uint128_4")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_4 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_5 "cxx11_tensor_uint128_5")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_5 PROPERTIES  LABELS "Unsupported")
ADD_TEST(cxx11_tensor_uint128_6 "cxx11_tensor_uint128_6")
SET_TESTS_PROPERTIES(cxx11_tensor_uint128_6 PROPERTIES  LABELS "Unsupported")
